project:
    name: "author-nonfiction"
    number: 9
repositories:
    - scooter-indie/author-nonfiction
defaults:
    priority: p1
    status: backlog
    labels:
        - pm-tracked
fields:
    priority:
        field: Priority
        values:
            p0: P0
            p1: P1
            p2: P2
    status:
        field: Status
        values:
            backlog: Backlog
            ready: Ready
            in_progress: "In progress"
            in_review: "In review"
            done: Done
triage:
    estimate:
        query: is:issue is:open -has:estimate
        apply: {}
        interactive:
            estimate: true
    tracked:
        query: is:issue is:open -label:pm-tracked
        apply:
            labels:
                - pm-tracked
            fields:
                priority: p1
                status: backlog
        interactive:
            status: true
